apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: todolist-deployment
spec:
  selector:
    matchLabels:
      app: todolist
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: prologic/todo:latest
        ports:
        - containerPort: 8000